variables:
  FOLDER: v1.15.0
  VERSION: "$FOLDER"
  TAGS: "${FOLDER}-dev latest-dev"
  RELEASE_DATE: 2019-06

build-v1.15.0:
  extends: .build
  
test-v1.15.0:
  extends: .test
  only:
    changes:
    - v1.15.0/*
